---
- name: Avi Controller | Services | Install the Avi Controller service file | New
  template: src=avicontroller.j2 dest=/usr/sbin/avicontroller mode=0755
  notify: Avi Controller | Services | Restart the avicontroller service

- name: Avi Controller | Services | {{ ansible_service_mgr }} | Install the Avi Controller service | New
  include: "{{ ansible_service_mgr }}/install.yml"

- name: Avi Controller | Services | {{ ansible_service_mgr }} | Start the service since it's not running |
  service: name=avicontroller enabled=yes state=started
  when: not con_desired_running.stdout
