#!/bin/sh
#
#       /etc/init.d/avicontroller
#
#       Daemon for avicontroller
#
# chkconfig:   2345 99 99
# description: Service for the Avi Controller

### BEGIN INIT INFO
# Provides:       avicontroller
# Required-Start: docker
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: start and stop avicontroller
# Description: Service for the Avi Controller
### END INIT INFO

case "$1" in
  start|restart|reload)
    /usr/sbin/avicontroller $1 &
    ;;
  stop|status)
    /usr/sbin/avicontroller $1
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|reload}"
    exit 2
esac

exit $?
